name: Deploy

# Uncomment this for monorepos
# defaults:
#   run:
#     working-directory: server

on:
  push:
    branches: [development, staging, main]
    # Uncomment this for monorepos
    # paths: ['server/**']

jobs:
  Development:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/development'

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets.DEVELOPMENT_AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy
        run: yarn run deploy  --stage development
        env:
          NODE_ENV: development
  Staging:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/staging'

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy
        run: yarn run deploy --stage staging
        env:
          NODE_ENV: staging

  Production:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy
        run: yarn run deploy --stage production
        env:
          NODE_ENV: production
